--Amazon Project--

CREATE TABLE amazon.sales_fact (
  order_id      text,
  order_date    date,
  product       text,
  category      text,
  sub_category  text,
  quantity      numeric(12,2),
  unit_price    numeric(12,2),
  discount      numeric(5,2),
  sales         numeric(14,2),
  profit        numeric(14,2),
  region        text,
  city          text,
  country       text,
  customer      text,
  yearmonth     text
);    



CREATE TABLE amazon.sales_fact_clean AS
SELECT 
    order_id,
    order_date,
    product,
    category,
    sub_category,
    quantity::int AS quantity,
    unit_price,
    discount,
    sales,
    profit,
    region,
    city,
    country,
    customer
FROM amazon.sales_fact
WHERE quantity > 0
  AND discount BETWEEN 0 AND 1
  AND sales >= 0
  AND profit IS NOT NULL;


--Business Questions + SQL Answers

--1.Top 10 Products by Total Sales Value:

SELECT product, SUM(sales) AS total_sales
FROM amazon.sales_fact_clean
GROUP BY product
ORDER BY total_sales DESC
LIMIT 10;

--2. Total Revenue Generated by Each Product Category

SELECT category, SUM(sales) AS total_revenue
FROM amazon.sales_fact_clean
GROUP BY category
ORDER BY total_revenue DESC;

--3. Average Order Value (AOV) per Customer

SELECT customer, ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS avg_order_value
FROM amazon.sales_fact_clean
GROUP BY customer
ORDER BY avg_order_value DESC;

--4. Most Profitable Regions

SELECT region, SUM(profit) AS total_profit
FROM amazon.sales_fact_clean
GROUP BY region
ORDER BY total_profit DESC;

--5. Top 5 Cities by Sales

SELECT city, SUM(sales) AS total_sales
FROM amazon.sales_fact_clean
GROUP BY city
ORDER BY total_sales DESC
LIMIT 5;

--6. Monthly Sales Trend

SELECT DATE_TRUNC('month', order_date) AS month, SUM(sales) AS monthly_sales
FROM amazon.sales_fact_clean
GROUP BY month
ORDER BY month;

--7. Customer Lifetime Value (CLV):Top 10 Customers

SELECT customer, SUM(sales) AS lifetime_value
FROM amazon.sales_fact_clean
GROUP BY customer
ORDER BY lifetime_value DESC
LIMIT 10;

--8. Top Sub-Categories by Profit

SELECT sub_category, SUM(profit) AS total_profit
FROM amazon.sales_fact_clean
GROUP BY sub_category
ORDER BY total_profit DESC
LIMIT 10;

--9. Discount Impact on Sales

SELECT discount, SUM(sales) AS sales_value
FROM amazon.sales_fact_clean
GROUP BY discount
ORDER BY discount;

--10. Profit Margin by Category

SELECT category, ROUND(SUM(profit) / SUM(sales) * 100, 2) AS profit_margin_percentage
FROM amazon.sales_fact_clean
GROUP BY category
ORDER BY profit_margin_percentage DESC;












  
